---
- name: Configure the service
  hosts: all
  gather_facts: false
  module_defaults: 
    ansible.builtin.template:
      owner: root
      group: root
      mode: '0644'
  tasks: 
  - name: Create directory /etc/containerd
    ansible.builtin.file: 
      path: /etc/containerd/
      state: directory
  - name: Create containerd config
    ansible.builtin.template: 
      src: ./templates/config.toml.j2
      dest: /etc/containerd/config.toml
  - name: Create containerd service file
    ansible.builtin.copy: 
      src: ./files/containerd.service
      dest: /etc/systemd/system/containerd.service
  - name: Run systemctl daemon-reload
    ansible.builtin.systemd: 
      daemon_reload: true
  - name: enabled containerd service
    ansible.builtin.systemd: 
      name: containerd
      enabled: true
  - name: enabled kubelet service
    ansible.builtin.systemd: 
      name: kubelet
      enabled: true
